#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Gurukul_MVP.Resource", IsApplication=true)]

namespace Gurukul_MVP
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010011
			public const int font = 2130771985;
			
			// aapt resource value: 0x7f01000a
			public const int fontProviderAuthority = 2130771978;
			
			// aapt resource value: 0x7f01000d
			public const int fontProviderCerts = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int fontProviderFetchStrategy = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int fontProviderFetchTimeout = 2130771983;
			
			// aapt resource value: 0x7f01000b
			public const int fontProviderPackage = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int fontProviderQuery = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int fontStyle = 2130771984;
			
			// aapt resource value: 0x7f010012
			public const int fontWeight = 2130771986;
			
			// aapt resource value: 0x7f010009
			public const int layout_aspectRatio = 2130771977;
			
			// aapt resource value: 0x7f010001
			public const int layout_heightPercent = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int layout_marginBottomPercent = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int layout_marginEndPercent = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int layout_marginLeftPercent = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int layout_marginPercent = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int layout_marginRightPercent = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int layout_marginStartPercent = 2130771975;
			
			// aapt resource value: 0x7f010004
			public const int layout_marginTopPercent = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int layout_widthPercent = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f070000
			public const int abc_action_bar_embed_tabs = 2131165184;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090000
			public const int notification_action_color_filter = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int notification_icon_bg_color = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int ripple_material_light = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int secondary_text_default_material_light = 2131296259;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080004
			public const int compat_button_inset_horizontal_material = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int compat_button_inset_vertical_material = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int compat_button_padding_horizontal_material = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int compat_button_padding_vertical_material = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int compat_control_corner_material = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int notification_action_icon_size = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int notification_action_text_size = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int notification_big_circle_margin = 2131230731;
			
			// aapt resource value: 0x7f080001
			public const int notification_content_margin_start = 2131230721;
			
			// aapt resource value: 0x7f08000c
			public const int notification_large_icon_height = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int notification_large_icon_width = 2131230733;
			
			// aapt resource value: 0x7f080002
			public const int notification_main_column_padding_top = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int notification_media_narrow_margin = 2131230723;
			
			// aapt resource value: 0x7f08000e
			public const int notification_right_icon_size = 2131230734;
			
			// aapt resource value: 0x7f080000
			public const int notification_right_side_padding_top = 2131230720;
			
			// aapt resource value: 0x7f08000f
			public const int notification_small_icon_background_padding = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int notification_small_icon_size_as_large = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int notification_subtext_size = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int notification_top_pad = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int notification_top_pad_large_text = 2131230739;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Aam = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Aam_txt = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Ainak = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Batak = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Bharath = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Chaata = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Dus = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Gamla = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int hindialphabet = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int homeIcon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int leftIcon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Makaan = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int matar = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int notification_action_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int notification_bg = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int notification_bg_low = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int notification_bg_low_normal = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int notification_bg_low_pressed = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int notification_bg_normal = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int notification_bg_normal_pressed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int notification_icon_background = 2130837524;
			
			// aapt resource value: 0x7f02001b
			public const int notification_template_icon_bg = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int notification_template_icon_low_bg = 2130837532;
			
			// aapt resource value: 0x7f020015
			public const int notification_tile_bg = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int notify_panel_notification_icon_bg = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int onclickactivities_u5 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int rightIcon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int soundIcon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Taala = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Font
		{
			
			// aapt resource value: 0x7f030000
			public const int hindifont = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int hindifontdisplay = 2130903041;
			
			static Font()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Font()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b002d
			public const int GuessEnglishWords = 2131427373;
			
			// aapt resource value: 0x7f0b002c
			public const int HindiVarnamala = 2131427372;
			
			// aapt resource value: 0x7f0b002e
			public const int MatchingGame = 2131427374;
			
			// aapt resource value: 0x7f0b001d
			public const int action_container = 2131427357;
			
			// aapt resource value: 0x7f0b0029
			public const int action_divider = 2131427369;
			
			// aapt resource value: 0x7f0b001e
			public const int action_image = 2131427358;
			
			// aapt resource value: 0x7f0b001f
			public const int action_text = 2131427359;
			
			// aapt resource value: 0x7f0b002a
			public const int actions = 2131427370;
			
			// aapt resource value: 0x7f0b0006
			public const int async = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int blocking = 2131427335;
			
			// aapt resource value: 0x7f0b000e
			public const int buttonHome = 2131427342;
			
			// aapt resource value: 0x7f0b0010
			public const int buttonNext = 2131427344;
			
			// aapt resource value: 0x7f0b000f
			public const int buttonPrev = 2131427343;
			
			// aapt resource value: 0x7f0b000c
			public const int buttonSound = 2131427340;
			
			// aapt resource value: 0x7f0b0011
			public const int button_Aa = 2131427345;
			
			// aapt resource value: 0x7f0b0012
			public const int button_Ai = 2131427346;
			
			// aapt resource value: 0x7f0b0017
			public const int button_Ba = 2131427351;
			
			// aapt resource value: 0x7f0b0018
			public const int button_Bha = 2131427352;
			
			// aapt resource value: 0x7f0b0016
			public const int button_Da = 2131427350;
			
			// aapt resource value: 0x7f0b0013
			public const int button_Ga = 2131427347;
			
			// aapt resource value: 0x7f0b0019
			public const int button_Ma = 2131427353;
			
			// aapt resource value: 0x7f0b0015
			public const int button_Ta = 2131427349;
			
			// aapt resource value: 0x7f0b0014
			public const int button_cha = 2131427348;
			
			// aapt resource value: 0x7f0b0028
			public const int chronometer = 2131427368;
			
			// aapt resource value: 0x7f0b0008
			public const int forever = 2131427336;
			
			// aapt resource value: 0x7f0b0021
			public const int icon = 2131427361;
			
			// aapt resource value: 0x7f0b002b
			public const int icon_group = 2131427371;
			
			// aapt resource value: 0x7f0b000d
			public const int imageView1 = 2131427341;
			
			// aapt resource value: 0x7f0b0024
			public const int info = 2131427364;
			
			// aapt resource value: 0x7f0b0009
			public const int italic = 2131427337;
			
			// aapt resource value: 0x7f0b0000
			public const int line1 = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int line3 = 2131427329;
			
			// aapt resource value: 0x7f0b001c
			public const int login = 2131427356;
			
			// aapt resource value: 0x7f0b001a
			public const int messageDisplay = 2131427354;
			
			// aapt resource value: 0x7f0b000a
			public const int normal = 2131427338;
			
			// aapt resource value: 0x7f0b0026
			public const int notification_background = 2131427366;
			
			// aapt resource value: 0x7f0b0022
			public const int notification_main_column = 2131427362;
			
			// aapt resource value: 0x7f0b0020
			public const int notification_main_column_container = 2131427360;
			
			// aapt resource value: 0x7f0b0025
			public const int right_icon = 2131427365;
			
			// aapt resource value: 0x7f0b0023
			public const int right_side = 2131427363;
			
			// aapt resource value: 0x7f0b0002
			public const int tag_transition_group = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int text = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int text2 = 2131427332;
			
			// aapt resource value: 0x7f0b000b
			public const int textForAam = 2131427339;
			
			// aapt resource value: 0x7f0b0027
			public const int time = 2131427367;
			
			// aapt resource value: 0x7f0b0005
			public const int title = 2131427333;
			
			// aapt resource value: 0x7f0b001b
			public const int username = 2131427355;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0c0000
			public const int status_bar_notification_info_maxnum = 2131492864;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int FlashCards = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int HindiVarnamala = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int notification_action = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_action_tombstone = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_template_custom_big = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_template_icon_group = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int notification_template_part_chronometer = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int notification_template_part_time = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int variousOptionsForKids = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int Aam = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Ainak = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Batakh = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int Bharath = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int Chaata = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int Dus = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int Gamla = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int Matar = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int Taala = 2131034120;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int status_bar_notification_info_overflow = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int TextAppearance_Compat_Notification = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int TextAppearance_Compat_Notification_Info = 2131361793;
			
			// aapt resource value: 0x7f0a0006
			public const int TextAppearance_Compat_Notification_Line2 = 2131361798;
			
			// aapt resource value: 0x7f0a0002
			public const int TextAppearance_Compat_Notification_Time = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int TextAppearance_Compat_Notification_Title = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int Widget_Compat_NotificationActionContainer = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int Widget_Compat_NotificationActionText = 2131361797;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			public static int[] PercentLayout_Layout = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 9
			public const int PercentLayout_Layout_layout_aspectRatio = 9;
			
			// aapt resource value: 1
			public const int PercentLayout_Layout_layout_heightPercent = 1;
			
			// aapt resource value: 6
			public const int PercentLayout_Layout_layout_marginBottomPercent = 6;
			
			// aapt resource value: 8
			public const int PercentLayout_Layout_layout_marginEndPercent = 8;
			
			// aapt resource value: 3
			public const int PercentLayout_Layout_layout_marginLeftPercent = 3;
			
			// aapt resource value: 2
			public const int PercentLayout_Layout_layout_marginPercent = 2;
			
			// aapt resource value: 5
			public const int PercentLayout_Layout_layout_marginRightPercent = 5;
			
			// aapt resource value: 7
			public const int PercentLayout_Layout_layout_marginStartPercent = 7;
			
			// aapt resource value: 4
			public const int PercentLayout_Layout_layout_marginTopPercent = 4;
			
			// aapt resource value: 0
			public const int PercentLayout_Layout_layout_widthPercent = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
